import streamlit as st
import datetime
import os
from dotenv import load_dotenv

IST = datetime.timezone(datetime.timedelta(hours=5, minutes=30))

# Local development: load keys from a .env file (does nothing on Streamlit
# Cloud, since there is no .env file there - see the block below instead).
load_dotenv()

# Streamlit Community Cloud: keys are provided via st.secrets (configured in
# the app's "Secrets" settings in the dashboard), not a .env file. Copy them
# into os.environ so the existing tools/model_loader code - which reads keys
# with os.getenv() - works completely unchanged, locally or in the cloud.
#
# Locally (no secrets.toml file at all - normal when just using .env), even
# checking st.secrets raises StreamlitSecretNotFoundError, so this whole
# block is wrapped in try/except and simply does nothing in that case -
# load_dotenv() above already handled local development.
try:
    for key in [
        "GROQ_API_KEY", "TAVILY_API_KEY", "OPENWEATHERMAP_API_KEY",
        "EXCHANGE_RATE_API_KEY", "GPLACES_API_KEY", "OPENAI_API_KEY",
    ]:
        if key in st.secrets:
            os.environ[key] = st.secrets[key]
except Exception:
    pass

from agent.agentic_workflow import GraphBuilder


def invoke_with_retry(react_app, messages, max_retries: int = 2):
    """
    Some models occasionally attempt a malformed inline tool call at the very
    end of a long generation (Groq error code 'tool_use_failed'). This is
    usually a one-off sampling glitch, not a repeatable failure - the same
    request frequently succeeds on a retry. Retry a few times specifically
    for this error before giving up; any other kind of error fails immediately.
    """
    last_error = None
    for attempt in range(1, max_retries + 2):
        try:
            return react_app.invoke(messages)
        except Exception as e:
            last_error = e
            if "tool_use_failed" in str(e) or "Failed to call a function" in str(e):
                print(f"[retry] attempt {attempt} hit tool_use_failed, retrying...")
                continue
            raise
    raise last_error

st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌍 Travel Planner Agentic Application")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat history
st.header("How can I help you in planning a trip? Let me know where do you want to visit.")

# Chat input box at bottom
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        with st.spinner("Bot is thinking..."):
            # Call the LangGraph agent directly in this same process, instead
            # of making an HTTP request to a separate FastAPI server - there
            # is no separate server process available on Streamlit Cloud.
            graph_builder = GraphBuilder(model_provider="groq")
            react_app = graph_builder()
            output = invoke_with_retry(react_app, {"messages": [user_input]}, max_retries=2)

            if isinstance(output, dict) and "messages" in output:
                answer = output["messages"][-1].content
            else:
                answer = str(output)

            if not answer or not str(answer).strip():
                answer = (
                    "The AI model returned an empty response for this request. "
                    "This can happen occasionally with some models - please try "
                    "asking again, or rephrase your request."
                )

        markdown_content = f"""# 🌍 AI Travel Plan

**Generated:** {datetime.datetime.now(IST).strftime('%Y-%m-%d at %H:%M')}
**Created by:** 😎Cool Dracula's Travel Agent

---

{answer}

---



*This travel plan was generated by AI. Kindly verify all information, especially prices, operating hours, and travel requirements before your trip. இந்த பயணத் திட்டம் AI மூலம் உருவாக்கப்பட்டது. உங்கள் பயணத்திற்கு முன், குறிப்பாக விலைகள், செயல்படும் நேரங்கள் மற்றும் பயணத்திற்குத் தேவையான விதிமுறைகள்/ஆவணங்கள் பற்றிய அனைத்து தகவல்களையும் சரிபார்த்துக் கொள்ளவும்.*
"""
        st.markdown(markdown_content)

    except Exception as e:
        st.error(f"The response failed due to: {e}")
